"""operationplanifiee id_machine nullable add id_service

Revision ID: 219f2db5bf56
Revises: 0f979440b441
Create Date: 2026-05-04 02:29:31.318250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219f2db5bf56'
down_revision: Union[str, Sequence[str], None] = '0f979440b441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operationplanifiee', sa.Column('id_service', sa.Integer(), nullable=True))
    op.alter_column('operationplanifiee', 'id_machine',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'operationplanifiee', 'service', ['id_service'], ['id_service'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operationplanifiee', type_='foreignkey')
    op.alter_column('operationplanifiee', 'id_machine',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('operationplanifiee', 'id_service')
    # ### end Alembic commands ###
