"""ajout tables service et piece externe

Revision ID: 3cfa73f3cebb
Revises: f814bd435a5e
Create Date: 2026-05-02 06:31:04.938884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfa73f3cebb'
down_revision: Union[str, Sequence[str], None] = 'f814bd435a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_externe',
    sa.Column('id_piece_externe', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_produit', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id_piece_externe')
    )
    op.create_table('service',
    sa.Column('id_service', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_produit', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type_service', sa.String(length=20), nullable=False),
    sa.Column('cout_horaire', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cout_fixe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.add_column('composant', sa.Column('id_service', sa.Integer(), nullable=True))
    op.add_column('composant', sa.Column('id_piece_externe', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'composant', 'piece_externe', ['id_piece_externe'], ['id_piece_externe'])
    op.create_foreign_key(None, 'composant', 'service', ['id_service'], ['id_service'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'composant', type_='foreignkey')
    op.drop_constraint(None, 'composant', type_='foreignkey')
    op.drop_column('composant', 'id_piece_externe')
    op.drop_column('composant', 'id_service')
    op.drop_table('service')
    op.drop_table('piece_externe')
    # ### end Alembic commands ###
