"""add_shift_config_and_duree_reelle

Revision ID: 4cf39ade8e41
Revises: f588c19b6fa3
Create Date: 2026-05-09 19:15:31.525739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf39ade8e41'
down_revision: Union[str, Sequence[str], None] = 'f588c19b6fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
