"""ajout_pause_pointage

Revision ID: 5c65fb48951f
Revises: e6d6047a2cfd
Create Date: 2026-05-11 12:59:54.823594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c65fb48951f'
down_revision: Union[str, Sequence[str], None] = 'e6d6047a2cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pausepointage',
    sa.Column('id_pause', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_op_plan', sa.Integer(), nullable=False),
    sa.Column('debut_pause', sa.DateTime(), nullable=False),
    sa.Column('fin_pause', sa.DateTime(), nullable=True),
    sa.Column('duree_min', sa.Integer(), nullable=True),
    sa.Column('motif', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_op_plan'], ['operationplanifiee.id_op_plan'], ),
    sa.PrimaryKeyConstraint('id_pause')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pausepointage')
    # ### end Alembic commands ###
