"""correction taille codes tracabilite

Revision ID: 7aec7f404f71
Revises: 83c580b8273a
Create Date: 2026-05-01 08:59:11.406705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aec7f404f71'
down_revision: Union[str, Sequence[str], None] = '83c580b8273a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commande', 'code_commande',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('lignecommande', 'code_ligne',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=11),
               existing_nullable=True)
    op.alter_column('ordrefabrication', 'code_of',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordrefabrication', 'code_of',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    op.alter_column('lignecommande', 'code_ligne',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('commande', 'code_commande',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
