"""ajout cancel_reason ligne commande

Revision ID: b0baf8be44d4
Revises: bb53629b9a5a
Create Date: 2026-05-01 13:40:49.426747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0baf8be44d4'
down_revision: Union[str, Sequence[str], None] = 'bb53629b9a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lignecommande', sa.Column('cancel_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lignecommande', 'cancel_reason')
    # ### end Alembic commands ###
