"""ajout piece_externe et service dans operation

Revision ID: e144a9902132
Revises: 8ec0aa7cdacf
Create Date: 2026-05-02 11:58:10.348193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e144a9902132'
down_revision: Union[str, Sequence[str], None] = '8ec0aa7cdacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('id_piece_externe', sa.Integer(), nullable=True))
    op.add_column('operation', sa.Column('id_service', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operation', 'piece_externe', ['id_piece_externe'], ['id_piece_externe'])
    op.create_foreign_key(None, 'operation', 'service', ['id_service'], ['id_service'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_column('operation', 'id_service')
    op.drop_column('operation', 'id_piece_externe')
    # ### end Alembic commands ###
