"""ajout_multi_taches_machine_service

Revision ID: e6d6047a2cfd
Revises: move_priorite_ofa
Create Date: 2026-05-11 11:36:18.339348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d6047a2cfd'
down_revision: Union[str, Sequence[str], None] = 'move_priorite_ofa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('multi_taches', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('service', sa.Column('multi_taches', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'multi_taches')
    op.drop_column('machine', 'multi_taches')
    # ### end Alembic commands ###
