"""add_shift_config_and_duree_reelle

Revision ID: f588c19b6fa3
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 17:14:04.005324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f588c19b6fa3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machineshiftconfig',
    sa.Column('id_config', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_machine', sa.Integer(), nullable=False),
    sa.Column('shift_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_machine'], ['machine.id_machine'], ),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.add_column('operationplanifiee', sa.Column('duree_reelle_min', sa.Integer(), nullable=True))
    op.drop_column('operationplanifiee', 'duree_estimee_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operationplanifiee', sa.Column('duree_estimee_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('operationplanifiee', 'duree_reelle_min')
    op.drop_table('machineshiftconfig')
    # ### end Alembic commands ###
