"""ajout prix_revient snapshots

Revision ID: f7b045b92c3f
Revises: 2466a6dad30b
Create Date: 2026-05-03 05:52:11.191027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b045b92c3f'
down_revision: Union[str, Sequence[str], None] = '2466a6dad30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composant', sa.Column('prix_revient', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('lignecommande', sa.Column('prix_revient_snapshot', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('ordrefabrication', sa.Column('prix_revient_snapshot', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordrefabrication', 'prix_revient_snapshot')
    op.drop_column('lignecommande', 'prix_revient_snapshot')
    op.drop_column('composant', 'prix_revient')
    # ### end Alembic commands ###
