"""ajout reference composant et couts operateur machine

Revision ID: f814bd435a5e
Revises: fed0bec774cc
Create Date: 2026-05-02 05:10:21.466176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f814bd435a5e'
down_revision: Union[str, Sequence[str], None] = 'fed0bec774cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composant', sa.Column('reference', sa.String(length=100), nullable=True))
    op.add_column('machine', sa.Column('cout_operateur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('machine', sa.Column('charge_operateur', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'charge_operateur')
    op.drop_column('machine', 'cout_operateur')
    op.drop_column('composant', 'reference')
    # ### end Alembic commands ###
