"""refonte nomenclature avec id auto

Revision ID: 2466a6dad30b
Revises: e144a9902132
Create Date: 2026-05-02 12:59:11.894846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2466a6dad30b'
down_revision: Union[str, Sequence[str], None] = 'e144a9902132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('id_nomenclature', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('nomenclature', 'id_composant',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomenclature', 'id_composant',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('nomenclature', 'id_nomenclature')
    # ### end Alembic commands ###
