"""ajout codes tracabilite

Revision ID: 83c580b8273a
Revises: 550bfbc8becb
Create Date: 2026-05-01 07:51:56.307207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c580b8273a'
down_revision: Union[str, Sequence[str], None] = '550bfbc8becb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commande', sa.Column('code_commande', sa.String(length=7), nullable=True))
    op.add_column('lignecommande', sa.Column('code_ligne', sa.String(length=10), nullable=True))
    op.add_column('ordrefabrication', sa.Column('code_of', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordrefabrication', 'code_of')
    op.drop_column('lignecommande', 'code_ligne')
    op.drop_column('commande', 'code_commande')
    # ### end Alembic commands ###
