"""id_machine nullable dans operation

Revision ID: 8ec0aa7cdacf
Revises: fe643176f9d8
Create Date: 2026-05-02 11:55:38.008358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec0aa7cdacf'
down_revision: Union[str, Sequence[str], None] = 'fe643176f9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'id_machine',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'id_machine',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
