"""ajout statut ligne commande

Revision ID: bb53629b9a5a
Revises: 7aec7f404f71
Create Date: 2026-05-01 11:39:03.403100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb53629b9a5a'
down_revision: Union[str, Sequence[str], None] = '7aec7f404f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lignecommande', sa.Column('statut', sa.String(length=20), nullable=False, server_default='on_hold'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lignecommande', 'statut')
    # ### end Alembic commands ###
