"""ajout plan_url assemblage

Revision ID: fed0bec774cc
Revises: b0baf8be44d4
Create Date: 2026-05-01 16:49:10.462227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed0bec774cc'
down_revision: Union[str, Sequence[str], None] = 'b0baf8be44d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblage', sa.Column('plan_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assemblage', 'plan_url')
    # ### end Alembic commands ###
